[package]
name = "cr8ts"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "2.1", features = ["chrono"] }
diesel-async = { version = "0.4", features = ["postgres"] }
rocket = { version = "0.5", features = ["json"] }
serde = "1.0"
rocket_db_pools = { version = "0.1", features = ["diesel_postgres"] }